[package]
   name = "campfire"
   version = "1.0.0"
   upgrade_policy = "compatible"

   [dependencies]
   Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
   
   [addresses]
   campfire = "0x0"